### ISSUE TITLE
Permission Denied when entering file name into terminal- use `cat`!

### ISSUE THREAD

**Issue by pprbckwrtr** [eeb177-W17/eeb177-W17.github.io#10]
I made a copy of the Marra2014_data.fasta file in my sandbox, and I tried doing #5 of 1.11.1 which says to "Replace the original “two-spaces” delimiter with a comma." This is a picture of all my various attempts which all resulted in a permission denied message. 
![screen shot 2017-01-23 at 7 12 52 pm](https://cloud.githubusercontent.com/assets/25047649/22232756/3882f954-e1a0-11e6-9c9f-686f5ce6d498.png)

**Comment by gauravsk** [comment]
You are attempting to run the file `my_file.fasta` as a program- you need to use `cat` or something similar to get the contents of the file to spit out onto the terminal screen. 

In general, if you are having errors while using pipe operators, try running the command one-by-one (i.e. one command, then two commands separated by a pipe, etc.)

**Comment by pprbckwrtr** [comment]
Ah got it! Thank you :D
