### ISSUE TITLE
HW #7, Wildcard "not a valid identifier"

### ISSUE THREAD

**Issue by pprbckwrtr** [eeb177-W17/eeb177-W17.github.io#13]
Hello,

I've been trying to do the loop for HW problem #7, and I used * .txt for the filename, but it says that it's not a valid identifier. Also tried "* .txt" and same thing. What am I doing wrong? 

Thanks!

PS I added the spaces there because it was italicizing my comment instead of showing the asterisk.

**Comment by gauravsk** [comment]
Can you please post the entire loop that you're trying to run, @pprbckwrtr?

**Comment by gauravsk** [comment]
BTW you can use the \` character (under the esc key on most keyboards) to identify chunks of code in these issues, using a language called markdown more here: [link](https://guides.github.com/features/mastering-markdown/). For example: `# here is some text formatted as code`
