### ISSUE TITLE
how to check if an object is an integer

### ISSUE THREAD

**Issue by junghoonkim0424** [eeb177-W17/eeb177-W17.github.io#14]
hi.

I don't get how to make a function distinguish between string and number.

here is my code,

def hw3_function(integer):
    if ((integer.isdigit())== "False"):
        return ("ERROR")
    elif (integer< 5):
        return print("Brr! It's cold!")
    elif (integer >25):
        return print("It's pretty warm!")
    elif ((integer >= 5) & (integer <= 25)):
        return print("What a pleasant temperature!")

if ((integer.isdigit())== "False") 

I just tried str.isdigit() function, but Is there better and easier way ??

thank you

**Comment by gauravsk** [comment]
This should help: https://eeb177-w17.github.io/2017/01/25/exercise3-python.html#Object-types

**Comment by junghoonkim0424** [comment]
solved by use type() command. Thank you.
