### ISSUE TITLE
setup for hw3 Software Carpentry python exercises

### ISSUE THREAD

**Issue by gauravsk** [eeb177-W17/eeb177-W17.github.io#15]
Hi everyone- please note that you will need to follow the setup instructions at [this link](http://swcarpentry.github.io/python-novice-inflammation/setup/) before you can complete the software carpentry exercises based on the inflammation data. The setup page linked above has a .zip file with all the required data- you'll need to provide a path to this data in your calls to the `numpy.loadtxt()` function.

**Comment by seanmathew95** [comment]
how do we provide the path to the function?

**Comment by gauravsk** [comment]
Providing paths in python is the same as in the terminal- e.g. if you want to import a file saved in the folder "eeb-177" folder on your desktop, we use `/home/eeb177-student/Desktop/eeb-177/<file_name>`. 

Try to avoid the `~/...` shortcut and instead provide the full path.
