### ISSUE TITLE
Is .pynb file for lab homework supposed to open up an R studio page? 

### ISSUE THREAD

**Issue by pprbckwrtr** [eeb177-W17/eeb177-W17.github.io#16]
I did: ipython notebook exercise-3-hw.ipynb 
This created the file, but when I open it, it's an RStudio file, and I am unable to type anything into it.

**Comment by pprbckwrtr** [comment]
Basically not sure how to get started. Any help would be really appreciated!

**Comment by gauravsk** [comment]
This is the easiest way to open a notebook:

1. In a terminal, navigate to the working directory where the .ipynb file is saved;  
2. Run `jupyter notebook`.  This should launch a browser tab.
3. Open your notebook from the browser.

**Comment by pprbckwrtr** [comment]
Thank you! Everything worked :)
