### ISSUE TITLE
fatal error when pushing !

### ISSUE THREAD

**Issue by mehdinj** [eeb177-W17/eeb177-W17.github.io#18]
I just tried to push my hw notebook file for week 3 for the final commit and I get the following error:
I don't know how to fix it
<img width="895" alt="screen shot 2017-02-01 at 4 30 06 pm" src="https://cloud.githubusercontent.com/assets/25048575/22532402/c1dd1674-e89b-11e6-9c6b-e63ef92d6b73.png">

**Comment by gauravsk** [comment]
@mehdinj, check out issue #9 and see if you can follow the instructions there. Otherwise no worries we can fix at some point soon (I won't be at lecture today, though)
