### ISSUE TITLE
I can't commit and push my file..

### ISSUE THREAD

**Issue by junghoonkim0424** [eeb177-W17/eeb177-W17.github.io#20]
Hi,

I created online github name as "eeb-177-final-project" repo.

and 

git remote add origin https://github.com/junghoonkim0424/eeb-177-final-project.git
git push -u origin master

use this command those commands on terminal.

somehow i succeeded git remote comand but always fail to "git push -u origin master" this command.

I have no idea what's the problem..

So at first , I create mkdir eeb-177-hw-project in eeb-177 folder, and the moved into the 

eeb-177-hw-project folder.  and then

git remote add origin https://github.com/junghoonkim0424/eeb-177-final-project.git
git push -u origin master

use those command.

Could you please figure out the problem what im doing wrong??

Thank you Gaurav.

**Comment by gauravsk** [comment]
Have you run `git init` in your project folder?
