### ISSUE TITLE
Having problem with hw4 ipython notebook file.

### ISSUE THREAD

**Issue by junghoonkim0424** [eeb177-W17/eeb177-W17.github.io#23]
Gaurav. I'm trying to add ,commit, and push the homework week 4 file but it complains.

eeb177-student@eeb177-VirtualBox:~/Desktop/eeb-177/homework$ git add week-4-hw-eeb177.ipynb
eeb177-student@eeb177-VirtualBox:~/Desktop/eeb-177/homework$ git commit -m "week-4-hw"
error: object file .git/objects/9c/587b6b784eeac2ba3e87f946b3dbabe89a79ca is empty
error: object file .git/objects/9c/587b6b784eeac2ba3e87f946b3dbabe89a79ca is empty
fatal: loose object 9c587b6b784eeac2ba3e87f946b3dbabe89a79ca (stored in .git/objects/9c/587b6b784eeac2ba3e87f946b3dbabe89a79ca) is corrupt

I don't get why it complains with "empty" and "corrupt" words.
It never happened before, so i'm confused.

**Comment by gauravsk** [comment]
Jung, can you try to see the recommendations in issue #9 and see if you can follow?
