### ISSUE TITLE
opening a csv file in jupyter...

### ISSUE THREAD

**Issue by kellybarr** [eeb177-W17/eeb177-W17.github.io#27]
I'm continually getting a encodedecode error when I use the open and read commands to try to access the beaks csv datafiles.  I've also tried the csv module, but to no avail.  Any thoughts on what gives?

**Comment by gauravsk** [comment]
Can you upload a screenshot of your python script and what happens when you do `less <filename>` in terminal?

**Comment by kellybarr** [comment]
![screen](https://cloud.githubusercontent.com/assets/22181126/22956084/aab1ae54-f2d4-11e6-88a5-67d3536ee4f8.png)

**Comment by kellybarr** [comment]
Actually, doing the less command made me realize that the header is what mattered.  I've got the data in Jupyter now by uploading the file sans header.

**Comment by gauravsk** [comment]
:100:
