### ISSUE TITLE
R Studio blank screen upon opening

### ISSUE THREAD

**Issue by mfsalama** [eeb177-W17/eeb177-W17.github.io#28]
I am hoping to start using R very soon for my project.. However, upon opening it, I only find a blank screen.. I see the window and options such as file, edit, code, view, plot, etc.. but there is absolutely nothing I can do.. it is all just a blank white screen.. any suggestions on how I can fix this problem? Thanks !

**Comment by gauravsk** [comment]
Run `sudo rstudio` from the terminal to get it to work! :ice_cream:
