### ISSUE TITLE
Final Project: Function has no errors, but no output produced (Code below)

### ISSUE THREAD

**Issue by ashenparikh** [eeb177-W17/eeb177-W17.github.io#29]
Goal: Trying to create a list of values for a given key in a dictionary. Any help would be greatly appreciated.

def completedic(filetext):
    Cult=open(filetext, "r", encoding = "ISO-8859-1")
    alldata=Cult.readlines() [1:]

    res = {}
    for line in alldata:
        elements = line.split (",")
        player = elements[0]
        data = elements[1:]
        #append new player by creating player and then add data, if player already there add data
        if player not in res.keys():
            res[player] = []
            res[player].append(data)
        else:
            res[player].append(data)

completedic("/home/eeb177-student/Desktop/eeb-177/eeb-174-final-project/CULT_data.csv")

**Comment by michaelalfaro** [comment]
ashen can you post some example data so we can try out the code?

**Comment by ashenparikh** [comment]
Sure, I attached below lines [1:10]


['\n', '40100,1,10,0,0,0.111111111,1,0.888888889,2.602,0.415307292,United States\n', '\n', '40100,1,6,0,0,0.2,1,0.888888889,4.751,0.67678503,United States\n', '\n', '40100,1,2,0,1,0.888888889,1,0.888888889,7.374,0.867703133,United States\n', '\n', '40100,1,4,0,0,0.666666667,1,0.888888889,6.927,0.840545188,United States\n', '\n']

**Comment by gauravsk** [comment]
Ashen your function as written doesn't return anything... Looks like you want to return the dictionary you are making.

**Comment by ashenparikh** [comment]
I see thank you very much. I'll add the respective returns for the function.

**Comment by gauravsk** [comment]
Please close this issue if this problem is resolved, or let us know if you need further advice.
