### ISSUE TITLE
Final Project: Function utilizing del function for dictionary

### ISSUE THREAD

**Issue by lsjkjs** [eeb177-W17/eeb177-W17.github.io#31]
My function utilizes the del function for the dictionary.
In column 7 of my Aves.csv file, there is information of whether the identified_name is a species, class, order, genus, or family. I want to extract only the species. In order to do so, I thought it would be best to put all the names and the rank in a dictionary and then delete from the dictionary, whose rank is not a "species". However, I get an error saying that since the dictionary is changing size, I cannot pass the loop. 
Is there a way around this where I can delete from the dictionary so that I only have the species?

def Lists_species(filename):
    Aves_species = {}
    file = open(filename, "r")
    all_records = file.readlines()[18:]
    for line in all_records:
        record_elements = line.split(",")
        name = record_elements[5]
        rank = record_elements[6]
        Aves_species[name] = rank
    for r in Aves_species.keys():
        if Aves_species[r] != "species":
            del Aves_species[r]
            D = dict(Aves_species)
    return Aves_species

**Comment by gauravsk** [comment]
It might be more efficient to include use the if-statement to build the dictionary in the first place (IE only populate the dictionary if you are on a Species row)
