### ISSUE TITLE
Gaurav what's this error message?

### ISSUE THREAD

**Issue by junghoonkim0424** [eeb177-W17/eeb177-W17.github.io#32]
eeb177-student@eeb177-VirtualBox:~/Desktop/eeb-177/homework$ git commit -m "week6hw"
error: object file .git/objects/9c/587b6b784eeac2ba3e87f946b3dbabe89a79ca is empty
error: object file .git/objects/9c/587b6b784eeac2ba3e87f946b3dbabe89a79ca is empty
fatal: loose object 9c587b6b784eeac2ba3e87f946b3dbabe89a79ca (stored in .git/objects/9c/587b6b784eeac2ba3e87f946b3dbabe89a79ca) is corrupt

I'm not able to commit and push the file to my homework repo.
The problem is if i upload the ipython notebook manually, it doesn't display images.
How could i fix this??

**Comment by gauravsk** [comment]
This was fixed by re-cloning the hw repo
