### ISSUE TITLE
Not Well Formatted PBDB file

### ISSUE THREAD

**Issue by erinsolis29** [eeb177-W17/eeb177-W17.github.io#33]
I have tried downloading my PBDB file both from the terminal and directly from the website, but whenever I perform a command for that file in the terminal, the contents of the file are random symbols. I tried to redownload the data again today using UCLA wifi, but I still get the random symbols, and I'm not sure how to fix it! Please help! I'm doing elephants!

**Comment by gauravsk** [comment]
This was fixed; file was being saved as XML after it was opened with gnumeric
