### ISSUE TITLE
Screenshots not showing up on github... pls halp D:

### ISSUE THREAD

**Issue by pprbckwrtr** [eeb177-W17/eeb177-W17.github.io#34]
Hello, 

I uploaded Part 1 of my HW to github, but I only now realized that my images aren't showing up on my github account even though they show up in my jupyter notebook. 

I tried doing the `![image](path)` method, but it wouldn't work (just simply no image), so I tried `<img src = "filename">` and it worked perfectly, but now the images won't show up on my github page even though they are in the notebook. This is all in markdown. 

What am I doing wrong? 

Thanks, 
Gayane

**Comment by pprbckwrtr** [comment]
P.S. And I tried doing `<img src = "path">` as well as `<img src = path>` and both just resulted in an image icon, not the actual screenshot, in the Jupyter notebook.

**Comment by pprbckwrtr** [comment]
`![image](path)` did not result in anything, however. I'd appreciate any help!!!

**Comment by gauravsk** [comment]
Let me know if you're still having this issue after we spoke today; if it's resolved, please close this issue.

**Comment by pprbckwrtr** [comment]
It still hasn't worked. I tried using the file paths instead of names this time. Are the path supposed to be copied from Github?

**Comment by gauravsk** [comment]
Gayane it looks like you're giving the full path to the file on your virtualbox- you should be giving the relative path on github. If the screenshots are saved in the same directory as the notebook you can just do `file-name.png`; if the screenshots in a subdirectory called "images" you can do `images/file-name.png`. we can do this in person next week if this still doesn't work.
