### ISSUE TITLE
splittling the csv file with split(",")

### ISSUE THREAD

**Issue by lsjkjs** [eeb177-W17/eeb177-W17.github.io#35]
Hello,

For both HW6 and for my function for the project, I am having trouble splitting the csv file with the comma delimeter.

Using linux, I changed the csv files to separate columns with the comma delimiter. 

However, when I utilize split to make a list of each line of the csv file, I get an empty list.

For example, 
file = open("Jiang2013-data.csv")
dictionary = {} #define dictionary
all_records = file.readlines()[1:] #read file
for line in all_records: #put taxon and r in dictionary
    record_elements = line.split(",")
    taxon = record_elements[2]
    r = record_elements[4]
    dictionary[taxon] = r
print(dictionary)

This code gives an empty dictionary. 

How do I read a column of the csv using split?
Please help!

**Comment by gauravsk** [comment]
I think the only issue here is that you are printing, and not returning, your dictionary. Recall that when you print, the output is spit onto the screen and vanishes forever; when you return, you can save the output dictionary and work with it later.
