### ISSUE TITLE
R Studio opens to just a white screen

### ISSUE THREAD

**Issue by kellybarr** [eeb177-W17/eeb177-W17.github.io#37]
And on that white screen, I can't type anywhere or access any of the drop-down menus.  Online, the solution seems to be to uninstall and reinstall.  I can't uninstall though.  I keep getting denied for not having permission through several different methods (dragging and dropping; rm -rf in unix).  Any solutions?

**Comment by gauravsk** [comment]
It should have been clarified in the email- you need to run RStudio as `sudo rstudio` from the terminal on the virtual box
