### ISSUE TITLE
Including Shell code in R paper format

### ISSUE THREAD

**Issue by erinsolis29** [eeb177-W17/eeb177-W17.github.io#39]
In lab, we learned how to incorporate our Python code into our R document for our final papers. How would we include the shell commands into the R document so that it turns out as code in the pdf as well? Thanks!

**Comment by gauravsk** [comment]
Good question, Erin. The code to do this is actually included at the bottom of the latest version of `demo-document.Rmd`, which you can get using a wget.

Basically we just need to open the shell code blocks with ` ```{bash, eval = FALSE}`
