### ISSUE TITLE
Appending - how to specify target file

### ISSUE THREAD

**Issue by chriscast123** [eeb177-W17/eeb177-W17.github.io#4]
I'm having trouble in regards to appending an output of a command to another file. I'm trying to append the order of the first 5 species in the data set to my week-2-hw-eeb174.txt. Every time I check the txt file nothing appears in there. Is there something I'm doing wrong? Am I appending it wrong? I provided screenshots so you can see what I'm doing. 
![screen shot 2017-01-21 at 11 25 36 pm](https://cloud.githubusercontent.com/assets/25042933/22185487/4f831f72-e09b-11e6-84a3-942ae9a18a22.png)
![screen shot 2017-01-21 at 11 26 03 pm](https://cloud.githubusercontent.com/assets/25042933/22185488/4f846710-e09b-11e6-9ef9-1162629489b3.png)

**Comment by chriscast123** [comment]
I was able to resolve the issue.

**Comment by gauravsk** [comment]
The issue here was that the redirect operator will make (or append) to a file in the current working directory (in Chris' case, `~/Desktop/CSB/unix/data`- to redirect to a file in a different folder, you can provide the full (or relative) path to the desired target.
