### ISSUE TITLE
Submission of final project

### ISSUE THREAD

**Issue by Krishna-K2609** [eeb177-W17/eeb177-W17.github.io#41]
Should the final report be submitted through CCLE in addition to github?

**Comment by gauravsk** [comment]
Let me ask Dr. Alfaro, Krishna.

@michaelalfaro Do you have preferences on how to receive submissions?

**Comment by michaelalfaro** [comment]
Yes please submit a pdf of the final report that includes a link to your github through the CCLE. Make sense?

**Comment by Krishna-K2609** [comment]
Sure! Quick question: how should we upload the PDF? Most of my other courses have an "Assignments" section through which I can upload files but I don't see that on my EEB234 page.


<img width="2020" alt="screen shot 2017-03-21 at 1 15 05 pm" src="https://cloud.githubusercontent.com/assets/25068687/24168721/6d05a874-0e38-11e7-8d17-d0b4fc87adbf.png">

**Comment by gauravsk** [comment]
Please upload a PDF and a link to your final project github repo on this CCLE submission page: https://ccle.ucla.edu/mod/assign/view.php?id=1467279&action=editsubmission
