### ISSUE TITLE
unix command 'cp' - how to specify target folder

### ISSUE THREAD

**Issue by junghoonkim0424** [eeb177-W17/eeb177-W17.github.io#6]
Hello,
I'm doing homework question 2, and trying to copy the text files in unix/data folder.
and then move it to the unix/sandbox/temp folder.

so what I though was copy all files ends with '.txt' and move it to temp folder.

Assume, I'm on the unix/data folder now.

then i typed $cp *.txt   /Desktop/eeb-177/CSB/unix/sandbox/temp

but it made an error.

Doesn't  cp *.txt copeis every text files in the folder?? 

I'm confused what i'm doing it wrong.

**Comment by junghoonkim0424** [comment]
I solved the issue.

**Comment by gauravsk** [comment]
The issue here is that the given file path lacked the shortcut to home, which is where the desktop folder lives (I.e. `~/Desktop/...`). I recommend that you always use tab complete to write out paths to avoid this issue.
