### ISSUE TITLE
how to extract specific lines from terminal history 

### ISSUE THREAD

**Issue by lsjkjs** [eeb177-W17/eeb177-W17.github.io#8]
I remember that we went over appending the command history in class but I have a question about appending specific lines from the history. For example, if I have 700 lines of command history and I want to append lines 600 to 650 to a file, what is a way to write this command?

**Comment by gauravsk** [comment]
You can cleverly combine the `head` and `tail` functions to achieve this- e.g. `history | head -n 650 | tail -n 50` (in words, extract the first 650 lines of history, then extract the last 50 lines of that).
