### ISSUE TITLE
"loose object" error in git

### ISSUE THREAD

**Issue by ciaoyee** [eeb177-W17/eeb177-W17.github.io#9]
When following the steps to commit a text file to the repository, doing "git add" doesn't cause any issue, but when I try to git commit -m "..." then it creates the error message:

![error message](https://cloud.githubusercontent.com/assets/25068121/22231537/11675704-e199-11e6-9f0c-9e4b650358a6.jpg)

I'm still not quite sure what's wrong, and most of the solutions I've found so far require that I restart my entire repository, so I was wondering if there was a solution that didn't require me restarting anything? Thanks in advance!

**Comment by gauravsk** [comment]
The best solution here will be to make a copy of the files updated since your last `git push`, clone your repo from github, and re-add the new `week-2-hw` file to the cloned repo. See me in class if you try this and this is still unclear.
